name: fast_barcode_scanner_platform_interface
description: A common platform interface for the fast_barcode_scanner plugin.
homepage: https://github.com/jhoogstraat/fast_barcode_scanner/tree/master/fast_barcode_scanner_platform_interface
repository: https://github.com/jhoogstraat/fast_barcode_scanner
version: 1.0.4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.1
dev_dependencies: 
  flutter_lints: ^1.0.4
